milvus-io/milvus-helm

- milvus-gpu/ci/db_backend/mysql_values.yaml
- milvus-gpu/ci/db_backend/sqlite_values.yaml
- milvus-gpu/values.yaml
> update config server

- milvus/ci/config/mysql/cpu/server_config.yaml
- milvus/ci/config/mysql/gpu/server_config.yaml
- milvus/ci/config/sqlite/cpu/server_config.yaml
- milvus/ci/config/sqlite/gpu/server_config.yaml
- milvus/ci/filebeat/values.yaml
- milvus/config/cpu/server_config.yaml
- milvus/config/gpu/server_config.yaml
- milvus/config/log_config.conf
- milvus/templates/engine/engine-deployment.yaml
- milvus/values.yaml
> Change milvus deploy path to /var/lib/milvus 

- milvus/templates/engine/engine-deployment.yaml
- milvus/values.yaml
> Update extraVolumes to list

- templates/_server_config.tpl
- values.yaml
> add monitor gateway addr

- ci/db_backend/mysql_gpu_values.yaml
- ci/db_backend/sqlite_gpu_values.yaml
> Add GPU sharing solution on native Kubernetes

- templates/_server_config.tpl
> fix cache_config in server_config

- templates/_server_config.tpl
- values.yaml
> Crud wal config

- templates/_server_config.tpl
> update and fix

- templates/readonly-deployment.yaml
- templates/writable-deployment.yaml
- values.yaml
> Add persistence mount path

- values.yaml
> Update mysql charts

- values.yaml
> Update Milvus server images tag

- templates/readonly-deployment.yaml
> Set the volume of Milvus readOnly node to readOnly

- templates/_helpers.tpl
Small fix for https://github.com/milvus-io/milvus-helm/issues/56
> Add missing service name for admin (#59) (#56)

- Chart.yaml
- README.md
- values.yaml
> Upgrade to v0.9.1

- templates/mishards-deployment.yaml
> Fix service name bug in mishards-deployment.yaml

- README.md
- templates/_readonly_server_config.tpl
- templates/_server_config.tpl
> Remove backend options

- templates/_readonly_server_config.tpl
- templates/_server_config.tpl
> Fix key name bug for milvus gpu configuration

- Chart.yaml
- README.md
- values.yaml
> Update helm version to 0.10.0

- .gitignore
- .helmignore
> Add gitignore and helmignore file

- README.md
- templates/admin-deployment.yaml
- templates/mishards-deployment.yaml
- templates/readonly-deployment.yaml
- templates/writable-deployment.yaml
- values.yaml
> Add restartPolicy & terminationGracePeriodSeconds

- charts/milvus/ci/db_backend/mysql_cpu_values.yaml
- charts/milvus/ci/db_backend/mysql_gpu_values.yaml
- charts/milvus/ci/db_backend/sqlite_cpu_values.yaml
- charts/milvus/ci/db_backend/sqlite_gpu_values.yaml
- charts/milvus/values.yaml
> Reduced request for resources

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/lint-test.yml
- README.md
- charts/milvus/.helmignore
- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/NOTES.txt
- charts/milvus/values.yaml
> Upgrade to v0.10.1

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Upgrade to v0.10.2

- charts/milvus/Chart.yaml
- charts/milvus/templates/config.yaml
- charts/milvus/templates/readonly-deployment.yaml
- charts/milvus/templates/writable-deployment.yaml
> rename server_config.yaml to milvus.yaml

- charts/milvus/README.md
- charts/milvus/templates/_readonly_server_config.tpl
- charts/milvus/templates/_server_config.tpl
- charts/milvus/values.yaml
> Add extra configuration

- charts/milvus/README.md
- charts/milvus/templates/_mishards_config.tpl
- charts/milvus/templates/mishards-rbac.yaml
- charts/milvus/values.yaml
> Add mishards-rbac.yaml

- charts/milvus/README.md
- charts/milvus/values.yaml
> Update docker images version to v0.10.3

- charts/milvus/Chart.yaml
- charts/milvus/templates/mishards-deployment.yaml
- charts/milvus/templates/readonly-deployment.yaml
>  When deploying Milvus Cluster, check the mysql startup status

- charts/milvus/templates/mishards-deployment.yaml
- charts/milvus/templates/readonly-deployment.yaml
> Merge 0.10.4 branch to 0.11.0

- charts/milvus/values.yaml
> Update configuration version to 0.6

- charts/milvus/templates/mishards-rbac.yaml
Configure role-based access control #129
> Configure role-based access control

- charts/milvus/Chart.yaml
- charts/milvus/templates/mishards-rbac.yaml
- charts/milvus/values.yaml
> Upgrade to v0.10.4

- charts/milvus/Chart.yaml
- charts/milvus/templates/mishards-rbac.yaml
- charts/milvus/templates/readonly-deployment.yaml
- charts/milvus/values.yaml
> Upgrade to v0.10.4 

- charts/milvus/templates/_readonly_server_config.tpl
- charts/milvus/templates/_server_config.tpl
- charts/milvus/values.yaml
> add log in milvus for 0.12.0

- charts/milvus/templates/_readonly_server_config.tpl
- charts/milvus/templates/_server_config.tpl
- charts/milvus/values.yaml
Signed-off-by: Xiangyu Wang <xiangyu.wang@zilliz.com>
> log.rotation_age

- charts/milvus/templates/_readonly_server_config.tpl
- charts/milvus/templates/_server_config.tpl
- charts/milvus/values.yaml
Signed-off-by: Xiangyu Wang <xiangyu.wang@zilliz.com>
> log.rotation_size

- charts/milvus/templates/_nginx_config.tpl
> update nginx timeout

- charts/milvus/templates/_nginx_config.tpl
- charts/milvus/templates/nginx-deployment.yaml
> No forward read api when readonly replicas is 0

- charts/milvus/templates/_nginx_config.tpl
> Nginx config

- charts/milvus/templates/_nginx_config.tpl
- charts/milvus/values.yaml
> add delay in nginx

- charts/milvus/templates/_nginx_config.tpl
- charts/milvus/values.yaml
> fix delay in nginx

- .github/workflows/lint-test.yml
- .github/workflows/release.yml
- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/requirements.lock
- charts/milvus/requirements.yaml
- charts/milvus/templates/pvc.yaml
- charts/milvus/values.yaml
- ct.yaml
No longer specify resources by default #147 
> No longer specify resources by default

- charts/milvus/templates/_nginx_config.tpl
> update grpc timeout in nginx

- .github/workflows/release.yml
* Upgrade to v0.10.2
* Add shards feature
* Update README
* Update values.yaml
* Add mishards-rbac.yaml
* Add mishards-rbac.yaml (#114)
* Upgrade to v0.10.3
* Update docker images version to v0.10.3 (#115)
* Add mishards-rbac.yaml
* Upgrade to v0.10.3
* Update mishards-rbac.yaml
Signed-off-by: quicksilver …
> Upgrade helm chart release action version to 0.10.5 (#156)

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Upgrade to v0.10.6

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Upgrade to 1.0.0

- charts/milvus/Chart.yaml
- charts/milvus/templates/readonly-deployment.yaml
- charts/milvus/templates/writable-deployment.yaml
- charts/milvus/values.yaml
> Optional extra labels for pod

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/readonly-deployment.yaml
- charts/milvus/templates/writable-deployment.yaml
- charts/milvus/values.yaml
> Upgrade to 1.0.1

- charts/milvus/Chart.yaml
- charts/milvus/templates/readonly-deployment.yaml
- charts/milvus/templates/writable-deployment.yaml
- charts/milvus/values.yaml
> Add extra env variable

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/readonly-deployment.yaml
- charts/milvus/templates/writable-deployment.yaml
- charts/milvus/values.yaml
> Upgrade to v1.1.0

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Upgrade Milvus version to 1.1.1

- charts/milvus/Chart.yaml
- charts/milvus/templates/_helpers.tpl
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/datanode-svc.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/indexnode-svc.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/querynode-svc.yaml
- charts/milvus/templates/servicemonitor.yaml
- charts/milvus/values.yaml
> Fix milvus worker node name bug

- charts/milvus/README.md
Signed-off-by: yanliang567 <yanliang.qiao@zilliz.com>
> [skip ci] Add example of expanding a Milvus cluster

- charts/milvus/Chart.yaml
Modified Milvus Helm chart description
> [skip ci] Modified Milvus Helm chart description

- OWMERS
> [skip ci] Update OWNERS

- OWMERS
- charts/milvus/README.md
Completely uninstall Milvus tips
> [skip ci] Completely uninstall Milvus tips

- .github/workflows/lint-test.yml
- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/proxy-deployment.yaml
- charts/milvus/templates/pulsar-standalone-deployment.yaml
- charts/milvus/templates/pvc.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
- charts/milvus/templates/standalone-deployment.yaml
- charts/milvus/values.yaml
Add Pulsar standalone data persistence volumes
/cc @zwd1208 
> Add Pulsar standalone data persistence volumes

- charts/milvus/Chart.yaml
- charts/milvus/templates/pulsar-standalone-deployment.yaml
Set pulsar defaultRetentionTimeInMinutes parameter to 10080
/cc @zwd1208 
> Set pulsar defaultRetentionTimeInMinutes parameter to 10080

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
Expose the bucketName configuration parameter
/cc @zwd1208 
> Expose the bucketName configuration parameter

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
Bumped milvus verison to 2.0.0-rc.2
/cc @zwd1208 
> Bumped milvus verison to 2.0.0-rc.2

- .github/workflows/checks.yaml
- .github/workflows/markdown.links.config.json
- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
Expose root of key prefix to etcd configuration
/cc @zwd1208 
> Expose root of key prefix to etcd configuration

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
Add retention time and retention size of rocksmq
/cc @zwd1208 
> Add retention time and retention size of rocksmq

- charts/milvus/README.md
Update REAMDE.md for service monitor
/cc @zwd1208 
> Update REAMDE.md for service monitor

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/proxy-deployment.yaml
- charts/milvus/templates/pvc.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
- charts/milvus/templates/standalone-deployment.yaml
- charts/milvus/values.yaml
Add Milvus logs data persistence volumes
/cc @zwd1208 
> Add Milvus logs data persistence volumes

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
Change the mount path of Milvus logs persistence volume
/cc @zwd1208 
> Change the mount path of Milvus logs persistence volume

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
Bumped milvus verison to v2.0.0-rc.3
/cc @zwd1208 
> Bumped milvus verison to v2.0.0-rc.3

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
Bumped milvus verison to 2.0.0-rc.4
/cc @zwd1208 
> Bumped milvus verison to 2.0.0-rc.4

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/_server_config.tpl
- charts/milvus/values.yaml
> add flags to log output on stdout & disk

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/pulsar-standalone-deployment.yaml
- charts/milvus/values.yaml
Bumped milvus verison to 2.0.0-rc.5
/cc @LoveEachDay 
> Bumped milvus verison to 2.0.0-rc.5

- charts/milvus/Chart.yaml
- charts/milvus/templates/pulsar-standalone-deployment.yaml
- charts/milvus/values.yaml
Upgrade pulsar standalone image version to 2.7.3
/cc @zwd1208 
> Upgrade pulsar standalone image version to 2.7.3

- .github/workflows/lint-test.yml
- .github/workflows/release.yml
- charts/minio/.helmignore
- charts/minio/Chart.yaml
- charts/minio/README.md
- charts/minio/templates/NOTES.txt
- charts/minio/templates/_helper_create_bucket.txt
- charts/minio/templates/_helpers.tpl
- charts/minio/templates/clusterroles.yaml
- charts/minio/templates/configmap.yaml
- charts/minio/templates/deployment.yaml
- charts/minio/templates/ingress.yaml
- charts/minio/templates/networkpolicy.yaml
- charts/minio/templates/poddisruptionbudget.yaml
- charts/minio/templates/post-install-create-bucket-job.yaml
- charts/minio/templates/post-install-prometheus-metrics-job.yaml
- charts/minio/templates/post-install-prometheus-metrics-role.yaml
- charts/minio/templates/post-install-prometheus-metrics-rolebinding.yaml
- charts/minio/templates/post-install-prometheus-metrics-serviceaccount.yaml
- charts/minio/templates/pvc.yaml
- charts/minio/templates/rolebindings.yaml
- charts/minio/templates/secrets.yaml
- charts/minio/templates/securitycontextconstraints.yaml
- charts/minio/templates/service.yaml
- charts/minio/templates/serviceaccount.yaml
- charts/minio/templates/servicemonitor.yaml
- charts/minio/templates/statefulset.yaml
- charts/minio/values.yaml
- ct.yaml
Add minio helm chart
/cc @zwd1208 
> Add minio helm chart

- .github/workflows/release.yml
Fix release milvus helm chart bug
/cc @zwd1208 
> Fix release milvus helm chart bug

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Bumped milvus verison to 2.0.0-rc.5-hotfix1

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Fix 2.0.0-rc5-hotfix1 image tag

- .gitignore
- charts/milvus/templates/config.tpl
Update .gitignore
/cc @zwd1208 
> [skip ci] Update .gitignore

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
Increase pulsar pvc storage from 5Gi to 10Gi.
> Increase pulsar storage size

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Bumped milvus verison to 2.0.0-rc.6

- OWNERS
- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Enable etcd auto compaction by revision

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
> Add msgChannel config to milvus.yaml

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Add CACHE_SIZE env to milvus components

- charts/milvus/Chart.yaml
- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
- charts/milvus/templates/standalone-deployment.yaml
> Fix milvus template with CACHE_SIZE env

- charts/milvus/Chart.yaml
- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
> Fix milvus template

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Bump milvus version to 2.0.0-rc.8

- charts/milvus/Chart.yaml
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
> Add rocksmq page size config

- charts/milvus/Chart.yaml
- charts/milvus/templates/config.tpl
> Add config root coord delta channel prefix

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Bump milvus version to v2.0.0-rc8-20211104-d1f4106

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Set autoBalance config to false

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Set retention size to 8GB and retention time to 7 days

- charts/milvus/Chart.yaml
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
> Add more milvus config

- charts/milvus/Chart.yaml
- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/proxy-deployment.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
- charts/milvus/templates/standalone-deployment.yaml
- charts/milvus/values.yaml
> Add health check for milvus components

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Enable compaction for data coordinator by default

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Disable data coordinator compaction by default

- charts/milvus/Chart.yaml
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
> Add gc config for data coordinator

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Enable compaction for data coordinator

- charts/milvus/Chart.yaml
- charts/milvus/templates/config.tpl
- ct.yaml
> Fix milvus etcd config when release name contains etcd

- charts/milvus/Chart.yaml
- charts/milvus/templates/_helpers.tpl
- charts/milvus/templates/insight-deployment.yaml
- charts/milvus/templates/insight-ingress.yaml
- charts/milvus/templates/insight-svc.yaml
- charts/milvus/values.yaml
/cc @LoveEachDay  @zwd1208 
- [ x ] Chart Version bumped
> Add insight to Milvus helm

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Refine memory settings for pulsar components

- charts/milvus/Chart.yaml
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
> Add rootPath config for minio

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> change bookkeeper replicas for pulsar

- charts/milvus/Chart.yaml
- charts/milvus/templates/config.tpl
> Fix minio and pulsar config when release name contains minio or pulsar

- charts/milvus/Chart.yaml
- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
> Add strategy config for coordinator

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Set pulsar backlog quota to 8G

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> enable autoBalance for queryCoordinator

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> change config for dataCoordinator

- charts/milvus/Chart.yaml
- charts/milvus/templates/ingress.yaml
- charts/milvus/templates/insight-ingress.yaml
> Fix the problem of ingress version mismatch

- charts/milvus/Chart.yaml
- charts/milvus/templates/servicemonitor.yaml
> modify the interval time for monitor

- charts/milvus/Chart.yaml
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
> Add parameters compaction for dataCoord

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Change config maxFieldNum for proxy

- charts/milvus/Chart.yaml
- charts/minio/Chart.yaml
- charts/minio/values.yaml
Keep minio pvc for milvus standalone when helm uninstall.
/cc @zwd1208 
> Keep minio pvc for milvus standalone

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Add GODEBUG env to release memory

- charts/milvus/Chart.yaml
- charts/milvus/templates/_helpers.tpl
- charts/milvus/templates/pulsar-podmonitor.yaml
- charts/milvus/values.yaml
> Add podMonitor for pulsar broker and proxy

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
- charts/minio/Chart.yaml
- charts/minio/README.md
> Bump milvus version to 2.0.0-pre-ga

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> change configuration for gc

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Increase etcd heartbeat timeout and election timeout

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> modify pulsar default version

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Downgrade pulsar image version to 2.7.3

- charts/milvus/Chart.yaml
- charts/milvus/templates/servicemonitor.yaml
- charts/milvus/values.yaml
> Make the parameter interval of serviceMonitor configurable

- charts/milvus/Chart.yaml
- charts/milvus/templates/ingress.yaml
Signed-off-by: shaoyue.chen <shaoyue.chen@zilliz.com>
Fix #289
/cc @LoveEachDay @Bennu-Li
> [milvus] Add default pathType for Ingress.HTTPIngressPath

- charts/milvus/Chart.yaml
- charts/milvus/templates/servicemonitor.yaml
- charts/milvus/values.yaml
> Add a configurable parameter scrapeTimeout to serviceMonitor

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Keep log pvc when release uninstalled

- charts/milvus/Chart.yaml
- charts/milvus/templates/_helpers.tpl
> change env HOST_URL for attu ingress

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Specify the attu image tag

- .github/workflows/release.yml
- charts/milvus/Chart.yaml
> Fix new pulsar chart release

- charts/milvus/Chart.yaml
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
> Fix pulsar empty port

- charts/milvus/Chart.yaml
- charts/milvus/templates/attu-ingress.yaml
- charts/milvus/templates/ingress.yaml
Fix ingress after first review :)
> [milvus] Fix issue ingress typo with backend.

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Bump milvus version to 2.0.2

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
Fix minio security issue: https://github.com/minio/minio/security/advisories/GHSA-m4qq-5f7c-693q
> Upgrade minio version to RELEASE.2022-03-17T06-34-49Z

- charts/milvus/Chart.yaml
- charts/milvus/templates/config.tpl
> Add default bufFlag config for milvus proxy

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Fix duplicate kafka env for MaxMessageBytes

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
> Add authorization config for milvus

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Add default values for ingress.annotations

- charts/milvus/Chart.yaml
- charts/milvus/requirements.lock
- charts/milvus/requirements.yaml
- charts/milvus/values.yaml
- ct.yaml
> Add kafka metrics

- .github/workflows/lint-test.yml
- .github/workflows/release.yml
> Fix github action after adding helm repo bitnami-pre-2022

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Refine kafka deployment

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
> Add more milvus configs for indexnode and indexcoord

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Bump milvus version to v2.1.0

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/proxy-deployment.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
- charts/milvus/templates/standalone-deployment.yaml
- charts/milvus/values.yaml
> Add heaptrack for milvus components

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/templates/configmap.yaml
- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/proxy-deployment.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
- charts/milvus/templates/standalone-deployment.yaml
- charts/milvus/values.yaml
> Refine milvus config

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Bump milvus version to v2.1.1

- charts/milvus/Chart.yaml
- charts/milvus/templates/config.tpl
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/values.yaml
> Enable disk for querynode and indexnode

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/templates/standalone-deployment.yaml
- charts/milvus/values.yaml
> Enable disk for milvus standalone

- charts/minio/Chart.yaml
- charts/minio/README.md
- charts/minio/templates/deployment.yaml
- charts/minio/templates/statefulset.yaml
- charts/minio/values.yaml
> Add health probe for minio

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Refine etcd image

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/proxy-deployment.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
- charts/milvus/templates/standalone-deployment.yaml
- charts/milvus/values.yaml
> Add continuous profiling with pyroscope

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
Resolves milvus-io/milvus#19174
> Refine kafka default replication factor

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Bump milvus version to v2.1.2

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Upgrade attu image version

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
> Add quota and limit configs for milvus

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
> Bump milvus version to v2.1.3

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Bump milvus version to v2.1.4

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Add ttl for puslar broker

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
> Add more config for milvus components

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
> modify quotaAndLimits params

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
> Refine data coordinator segment config

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
Signed-off-by: bigsheeper <yihao.dai@zilliz.com>
> Enable quota and limits in helm

- charts/milvus/Chart.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/standalone-deployment.yaml
- charts/milvus/values.yaml
> Add local storage size limit

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
Signed-off-by: bigsheeper <yihao.dai@zilliz.com>
> Update maxTtDelay in helm

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Change params for values.yaml

- .github/workflows/markdown.links.config.json
- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Enable disk index by default

- charts/milvus/Chart.yaml
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
#386 
Signed-off-by: zhagnlu <lu.zhang@zilliz.com>
>  Add parameter threadCoreCoefficient (#386)

- charts/milvus/Chart.yaml
- charts/milvus/templates/config.tpl
> Fix invalid yaml comment

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
> Bump milvus version to 2.2.0

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Change default log level to info

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
> Add tenant namespace and auth parameters for external pulsar

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Upgrade attu image tag

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Fix milvus config tools for printing config into log

- README.md
The origin logo returns 404， fix the logo with the master's one
> fix the broken logo

- charts/milvus/Chart.yaml
- charts/milvus/requirements.lock
- charts/milvus/requirements.yaml
- charts/milvus/values.yaml
> Bump milvus version to v2.2.2

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
- charts/milvus/values.yaml
> Enable active standby for milvus coordinator components

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Update attu version to 2.2.2

- charts/milvus/README.md
/cc @zwd1208 @Bennu-Li @locustbaby 
> Refine readme with how to enable log to file

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Bump milvus version to 2.2.3

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Bump attu version to 2.2.3

- .github/mergify.yml
> Add mergify rules for ci

- .github/workflows/lint-test.yml
- .github/workflows/release.yml
Remove checkout and release only on tag with version
> Remove checkout and release only on tag with version

- charts/milvus/README.md
- charts/milvus/templates/ingress.yaml
- charts/milvus/values.yaml
config ingress' path into values
> config ingress' path into values

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/_helpers.tpl
- charts/milvus/templates/mixcoord-deployment.yaml
- charts/milvus/templates/mixcoord-svc.yaml
- charts/milvus/values.yaml
> add mixcoord

- .github/mergify.yml
- .github/workflows/release.yml
> fix release

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Bump attu version to 2.2.4

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Bump to 2.3.0-beta

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Downgrade milvus version to 2.2.4

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Bump milvus to 2.2.5

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Bump to 2.2.6

- charts/milvus/Chart.yaml
> Bump chart version

- charts/milvus/Chart.yaml
- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/proxy-deployment.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
- charts/milvus/templates/standalone-deployment.yaml
> Fix heaptrack

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
- charts/minio/README.md
> Bump milvus version to v2.2.7

- charts/minio/Chart.yaml
/cc @zwd1208 @Bennu-Li @locustbaby @haorenfsa 
> Bump minio version for updating doc

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
/cc @zwd1208 @Bennu-Li @locustbaby @haorenfsa 
> Bump milvus version to v2.2.8

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Shortening the subscriptionExpirationTimeMinutes of pulsar

- charts/milvus/Chart.yaml
- charts/milvus/templates/standalone-deployment.yaml
Fix volume mounts for milvus standalone
> Fix heaptrack volume mounts for milvus standalone

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/standalone-deployment.yaml
- charts/milvus/values.yaml
> Bump milvus version to v2.2.9

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Bump milvus version to 2.2.10

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Bump milvus version to 2.2.11

- charts/milvus/Chart.yaml
> Fix milvus app version

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
> Bump milvus version to 2.2.13

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
> Update attu version
