milvus-io/milvus-helm

- templates/writable-deployment.yaml
Set Recreate Deployment for Milvus writable node. fix #79
> Set Recreate Deployment for Milvus writable node (#79)

- templates/readonly-deployment.yaml
- templates/writable-deployment.yaml
If I hava `conf.yaml`. 
```
$ cat conf.yaml
persistence:
enabled: true
persistentVolumeClaim:
existingClaim: "milvus-data"
logsPersistence:
enabled: true
persistentVolumeClaim:
existingClaim: "milvus-log"
$ helm install --dry-run --name=milvus -f conf.yaml ./milvus-helm
```
It will report the follow error:
```
Error: render error in "milvus/templates/writable-deployment.yaml": template: milvus/templates/writable-deployment.yaml:128:94: executing "milvus/templates/writable-deployment.yaml" at <printf>: wrong number of args for printf: want at least 1 got 0
```.
> Fix "wrong number of args for printf: want at least 1 got 0"

- charts/milvus/Chart.yaml
- charts/milvus/templates/readonly-deployment.yaml
When neither mysql nor externalMysql is enabled, a syntax error is produced. This fixes it.
> Fixed syntax error when neither mysql nor externalMysql is enabled

- charts/milvus/templates/readonly-deployment.yaml
Fixed specify readonly resources doesn't take effect bug #123 
> Fixed specify readonly resources doesn't take effect bug

- charts/milvus/templates/mishards-rbac.yaml
Fix ClusterRole resource conflict bug
> Fix ClusterRole resource conflict bug

- charts/milvus/templates/nginx-deployment.yaml
> Disable check readonly node ready status when readonly replicas is 0

- charts/milvus/templates/_nginx_config.tpl
Comment out the access_log parameter in Nginx configuration file
> Comment out the access_log parameter in Nginx configuration file

- charts/milvus/README.md
- charts/milvus/templates/NOTES.txt
- charts/milvus/templates/_readonly_server_config.tpl
- charts/milvus/templates/_server_config.tpl
- charts/milvus/templates/readonly-deployment.yaml
- charts/milvus/templates/readonly-svc.yaml
- charts/milvus/templates/writable-deployment.yaml
- charts/milvus/templates/writable-svc.yaml
- charts/milvus/values.yaml
Define liveness and readiness probes uses an HTTP GET request
> Define liveness and readiness probes uses an HTTP GET request

- charts/milvus/Chart.yaml
- charts/milvus/templates/_helpers.tpl
- charts/milvus/templates/_mishards_config.tpl
- charts/milvus/templates/mishards-deployment.yaml
Using mysql+pymysql: scheme for SQLALCHEMY_DATABASE_URI.
mishards already have installed `PyMySQL`, so using `mysql+pymysql://` as a connection scheme is enough, we could remove install `mysqlclient` during the container's startup.
> improvment: mysql connection string for sqlalchemy.

- charts/milvus/Chart.yaml
Fix the link for Milvus logo in Chart.yaml
> Fix the link for Milvus logo in Chart.yaml

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/_readonly_server_config.tpl
- charts/milvus/templates/_server_config.tpl
- charts/milvus/templates/pvc.yaml
- charts/milvus/templates/readonly-deployment.yaml
- charts/milvus/templates/writable-deployment.yaml
- charts/milvus/values.yaml
As milvus 1.1.1 has been released, and s3 is supported default by official images.
This supports s3 storage for cluster deployment with helm.
related issue: https://github.com/milvus-io/milvus/issues/5335
Signed-off-by: Ji Bin <matrixji@live.com>
> feature: add s3 storage support

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/hpa.yaml
- charts/milvus/values.yaml
This feature supports the horizontal pod auto scaler for milvus
/cc @zwd1208 
> HorizontalPodAutoscaler support

- .github/stale.yml
Closes abandoned issues after a period of inactivity
/cc @zwd1208 
> [skip ci] Closes abandoned issues after a period of inactivity

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
Increase the default pulsar pvc storage to 100GB.
/cc @zwd1208 
> Increase the default pulsar pvc storage to 100GB

- charts/milvus/Chart.yaml
- charts/milvus/templates/standalone-deployment.yaml
Set milvus standalone upgrade strategy to `recreate`.
/cc @zwd1208 
> Set milvus standalone upgrade strategy to recreate

- charts/milvus/Chart.yaml
- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/proxy-deployment.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
- charts/milvus/templates/standalone-deployment.yaml
- charts/milvus/values.yaml
Signed-off-by: jeffzzhang <jeffzzhang@tencent.com>
Add CACHE_SIZE env to milvus components deployments
/cc @LoveEachDay @zwd1208 
> Add CACHE_SIZE env to milvus components deployments

- charts/milvus/Chart.yaml
- charts/milvus/ci/cluster-values.yaml
- charts/milvus/values.yaml
Pulsar 2.7.3 uses old log4j2 version and contains security vulnerability. 
Pulsar 2.8.4 fixes those security issues.
> Upgrade pulsar from 2.7.3 to 2.8.2

- charts/milvus/Chart.yaml
- charts/milvus/templates/config.tpl
`retentionDuration` config has been moved from `dataCoord` section to `common`.
> Fix retention duration config

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
> Add support for using pulsar or kafka as milvus standalone message queue

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
Allows to configure Kafka SASL/PLAIN or PLAIN authentication for external kafka. External kafka could be a managed kafka cluster (e.g. Amazon MSK or Confluent), which requires authentication.
- The service side code seems to be handle this already -https://github.com/milvus-io/milvus/blob/4ae1ca2cacc15e03afd8853ab4dedf10ba61a2d6/internal/util/paramtable/base_table.go#L186.
- fixes #340 
Please let me know if any more changes are required in this PR.
> [milvus] externalKafka: Allow configuring kafka sasl_plain authentication

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
Recently many users encountered etcd pod keeping crash issue because of `empty member_id`, we try to fix the issue in our fork at https://github.com/milvus-io/bitnami-docker-etcd.
For now we'll use this fork to build etcd image which is published  at `milvusdb/etcd`. 
> Use new etcd image to mitigate etcd pod crash

- charts/milvus/README.md
`charts/milvus/README.md` was messed up in former PR #333 . This PR fixes conflict markers left inside.
> Fix conflict markers in README.md

- charts/milvus/README.md
Fix version requirement for Attu.
The Attu ingress template uses `pathType`, which is only available in k8s 1.18+ https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/
> [Milvus] Fix version requirement for Attu

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/_helpers.tpl
- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/proxy-deployment.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
- charts/milvus/templates/serviceaccount.yaml
- charts/milvus/templates/standalone-deployment.yaml
- charts/milvus/values.yaml
This adds the ability to create and use a service account for the Milvus components.  This can be useful for adding annotations to a service account for things like IRSA in EKS to inject a IAM role for Minio/S3 (https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/). Example use in the chart:
```
serviceAccount:
create: true
name:
annotations:
eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/milvus-s3
```
> Milvus - Add / Customize Service Account

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/templates/configmap.yaml
- charts/milvus/templates/datacoord-deployment.yaml
- charts/milvus/templates/datanode-deployment.yaml
- charts/milvus/templates/indexcoord-deployment.yaml
- charts/milvus/templates/indexnode-deployment.yaml
- charts/milvus/templates/proxy-deployment.yaml
- charts/milvus/templates/querycoord-deployment.yaml
- charts/milvus/templates/querynode-deployment.yaml
- charts/milvus/templates/rootcoord-deployment.yaml
- charts/milvus/templates/standalone-deployment.yaml
- charts/milvus/values.yaml
Allow you to user specify extra config for milvus, which has the top priority. Now we have the config merge in the following order:
1. merge the configmap generated by the helm-chart with the `milvus.yaml` in the milvus image
2. merge the extra config `user.yaml` with the step 1 result as the final `milvus.yaml`
So you can specify extra config even if it doesn't support declare in the values.yaml.
/hold
> Add dynamic config for milvus

- charts/milvus/Chart.yaml
- charts/milvus/values.yaml
Orphaned pulsar subscription will block message producing due to blacklog quota. Enable pulsar subscription expiration will automatically remove subscription which has no consumers. 
> Enable pulsar subscription expiration after 30 minutes

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/config.tpl
- charts/milvus/values.yaml
1. Remove milvus helm default config options, using milvus.yaml in image instead;
2. If you want to override default config options, set in `extraConfigFiles.user.yaml` instead;
3. Bump milvus version to v2.2.1
> Refine milvus config parameters

- charts/minio/Chart.yaml
- charts/minio/templates/podmonitor.yaml
- charts/minio/templates/post-install-prometheus-metrics-job.yaml
- charts/minio/templates/post-install-prometheus-metrics-role.yaml
- charts/minio/templates/post-install-prometheus-metrics-rolebinding.yaml
- charts/minio/templates/post-install-prometheus-metrics-serviceaccount.yaml
- charts/minio/templates/servicemonitor.yaml
- charts/minio/values.yaml
1. update the metrics path from `/minio/prometheus/metrics` to `/minio/v2/metrics/cluster`
2. add podMonitor for minio
> minio add podmonitor and update metrics path

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/values.yaml
By default, the kafka chart enabled time based retention (7 day) and size based retention (1GB). We'd keep consistent settings for all message queues. So we'd only used time based retention and keep 7 days as default.
And kafka log retention is based on `log segment`, and default `log.roll.hours` is 168 (7 days), so we'd keep a log for at most 14 days. Here we'd decrease `log.roll.hours` to 24 (1 day).
/cc @zwd1208 @Bennu-Li @locustbaby 
> Decrease kafka log segment roll duration

- charts/milvus/Chart.yaml
- charts/milvus/README.md
- charts/milvus/templates/service.yaml
- charts/milvus/values.yaml
Hi! We're running milvus behind Istio service mesh. In order to help Istio proxy TCP traffic to Milvus service, we either need to add the protocol in the name, e.g `grpc-milvus`, or specify `appProtocol: grpc` in the port definition. Both options would work for me, I consider the first one to be less obscure, so I simply added single new `portName` variable in the chart template. So far each time I am upgrading the chart - I am doing this fix manually.
More about Istio protocol selection: [here](https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/)
Thanks!
> [Milvus]: service portName value templating

- charts/milvus/templates/attu-svc.yaml
- charts/milvus/values.yaml
Fixes #459. A typo prevented usage of a given load balancer IP for the Attu service. 
This PR does the two following changes: 
- Fixes the condition checking for existence of the loadBalancerIP field in the `values.yaml` file, but using another field when passing the value of the loadBalancerIP to the service
- Adds an option to specify a loadBalancerIP for the Attu service (which exists in the template, but was missing in `values.yaml`)
> [milvus] attu-svc: fix loadBalancerIP issue

- charts/minio/Chart.yaml
- charts/minio/templates/_helpers.tpl
- charts/minio/templates/poddisruptionbudget.yaml
This pull request aims to update the Minio Pod Disruption Budget (PDB) API version from "policy/v1beta1" to "policy/v1" in version 1.25.
As of Kubernetes version 1.25, the "policy/v1beta1" API version for Pod Disruption Budget has been deprecated, and the recommended default API version is "policy/v1". 
> [milvus-minio]Minio pdb apiversion support

- charts/milvus/templates/attu-svc.yaml
The [default values file](https://github.com/milvus-io/milvus-helm/blob/405dd7b38cfb38cf3eec91971983d763551d9640/charts/milvus/values.yaml#L408) has a `port` field, which is never used. This PR makes the `attu-svc` template use the specified value.
This enables setting the port for Attu exposition to any value. The current behavior ignores what is given in the values file and always uses `3000`.
> [milvus] attu-svc: allow changing service port from values file
